### ISSUE TITLE
This mod Crashes on mobile

### ISSUE THREAD

**Issue by WilloIzCitron** [Xeloboyo/PvP-Notifs#1]
reproducing:
installing this mod on mobile

im want install this mod on mobile and but im restaring a game and launching a game, crashed

crash log:
[crash_1614853196524.txt](https://github.com/Xeloboyo/PvP-Notifs/files/6082782/crash_1614853196524.txt)

**Comment by Xeloboyo** [comment]
Looks like tile for-each is a bit inconsistent, thanks, will replace with something else.

**Comment by Xeloboyo** [comment]
Fixed

**Comment by WilloIzCitron** [comment]
thanks
