### ISSUE TITLE
Mono Building when activated gamma ai

### ISSUE THREAD

**Issue by Hot-Sausage07** [Xeloboyo/PvP-Notifs#2]
![image](https://user-images.githubusercontent.com/78838382/110479386-49adde00-8120-11eb-9367-729e1172fca5.png)

**Comment by Xeloboyo** [comment]
thanks, will fix.

**Comment by Xeloboyo** [comment]
Fixed

**Comment by Hot-Sausage07** [comment]
:D thanks
